import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import React, {ReactNode} from "react";
import "../styles/globals.scss";
import {RootLayoutFeature} from "@/layouts/RootLayoutFeature";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RBC ID",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{  children: ReactNode; }>) {
  return (
    <html lang="ru">
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </Head>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <RootLayoutFeature>
      {children}
    </RootLayoutFeature>
    </body>
    </html>
  );
}
